[package]
name = "dancing_links_x"
version = "0.1.0"
edition = "2024"
# default-run = "Sudoku"
default-run = "NQueens"

[profile.release]
lto = "thin"
overflow-checks = false
opt-level = 3
strip = "none"
debug-assertions = false


[dependencies]
itertools = "0.14.0"
